mekona_solution/mekona_solution/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('control/', include('order_control.urls')),
    path('', RedirectView.as_view(url='/control/', permanent = True)),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')))
]

mekona_solution/order_control/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainpage, name = 'mainpage_url'),
    path('history/', views.historypage, name = 'history_url'),
    
    path('order_list/', views.OrderList.as_view(), name = 'order_list_url'),
    path('order/<int:order_id>', views.order_detail, name="order_detail_url"),
    path('order_create/', views.OrderCreate.as_view(), name = 'order_create_url'),
    path('order/<int:obj_id>/order_update/', views.OrderUpdate.as_view(), name="order_update_url"),
    path('order/<int:obj_id>/order_delete/', views.OrderDelete.as_view(), name="order_delete_url"),
    #path('order/<int:order_id>/order_pdf/', views.html_to_pdf_view, name="order_pdf_url"),
    
    
    path('task_list/', views.TaskList.as_view(), name = 'task_list_url'),
    path('task/<int:task_id>', views.task_detail, name="task_detail_url"),
    path('task_create/', views.TaskCreate.as_view(), name = 'task_create_url'),
    path('task/<int:obj_id>/task_update/', views.TaskUpdate.as_view(), name="task_update_url"),
    path('task/<int:obj_id>/task_delete/',  views.TaskDelete.as_view(), name="task_delete_url"),
    
    path('account/', views.UserUpdateView.as_view(), name="profile_detail_url"),
    path('account/update', views.UserUpdateView.as_view(), name="profile_update_url"),
    path('account/orders', views.ClientOrderListView.as_view(), name="user_orders_detail_url"),
    path('account/tasks_worker', views.WorkerTaskListView.as_view(), name="worker_tasks_url"),
    path('account/tasks_admin', views.AdminTaskListView.as_view(), name="admin_tasks_url"),
]

mekona_solution/order_control/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


class Type_of_work(models.Model):
    name_of_type = models.CharField(max_length = 200, 
                                    verbose_name = 'Виды работ')
    class Meta:
        verbose_name = 'Вид работы'
        verbose_name_plural = 'Виды работ'

    def __str__(self):
        return self.name_of_type

class Profile(models.Model):
    # CASCADE means if the user is deleted the profile is deleted
    # However, If the profile is deleted, the user is not deleted.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} Profile'

    def get_absolute_url(self):
        return reverse("profile_detail", kwargs={"user_id": self.user.pk})
    
    def get_update_url(self):
        return reverse("profile_update_url", kwargs={"user_id": self.user.pk})


class Order(models.Model):
    order_author = models.ForeignKey(User, on_delete=models.CASCADE,
                                    verbose_name = 'Автор' )
    order_text = models.TextField(verbose_name = 'Текст')
    order_date_creation = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата создания')
    order_date_update = models.DateTimeField(auto_now=True,
                                    verbose_name='Дата изменения', 
                                    blank=True, null=True)
    type_of_work_fk = models.ManyToManyField(Type_of_work, through = 'Order_Type', 
                                    verbose_name = 'Виды работ')
    client_number = PhoneNumberField(verbose_name = 'Номер обратной связи') #  +7(222)-222-23-23
    deadline = models.DateField(blank=True, null=True, 
                                    verbose_name= 'Дата окончания')
                    
    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
    
    def __str__(self):
        return '{} {} | {}'.format(self.order_author.first_name, self.order_author.last_name,  self.order_date_creation)
    
    def get_absolute_url(self):
        return reverse("order_detail_url", kwargs={"order_id": self.pk})
    
    def get_update_url(self):
        return reverse("order_update_url", kwargs={"obj_id": self.pk})

    def get_delete_url(self):
        return reverse("order_delete_url", kwargs={"obj_id": self.pk})

class Order_Type(models.Model):
    type_fk = models.ForeignKey(Type_of_work, on_delete=models.CASCADE)
    order_fk = models.ForeignKey(Order, on_delete=models.CASCADE)
    count = models.FloatField(verbose_name = 'Стоимость', blank=True, null=True)

    class Meta:
        verbose_name = 'Вид работ в заказе'
        verbose_name_plural = 'Виды работ в заказе'

class Task(models.Model):
    type_fk = models.ForeignKey(Type_of_work, verbose_name = 'Тип работ',
                                blank=True, null=True, 
                                on_delete=models.SET_NULL)
    order_fk = models.ForeignKey(Order, verbose_name = 'Заказ', blank=True,
                                null=True, on_delete=models.SET_NULL)
    task_author = models.ForeignKey(User, on_delete=models.CASCADE,
                                verbose_name = 'Отвественный', related_name= '+' )
    task_executor  = models.ForeignKey(User, on_delete=models.SET_NULL,
                                verbose_name = 'Исполнитель', blank=True, null=True, related_name = '+')

    TASK_STATUS = (
        ('L', 'Принята в обработку'),
        ('С', 'Выполнена'),
        ('F', 'Отменена'),
    )

    status = models.CharField(max_length=1, choices=TASK_STATUS,
                                default='L', verbose_name = 'Cтатус',
                                help_text='Статус задачи')   

    
    task_text = models.CharField(max_length=250, verbose_name = 'Описание задачи')
    task_date_creation = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата создания')
    task_date_comleate = models.DateTimeField(verbose_name='Дата завершения', 
                                    blank=True, null=True)
                            
    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задача'
        

    def __str__(self):
        return 'Отвественный: {}, Исполнитель: {}'.format(self.task_author, self.task_executor)

    def get_absolute_url(self):
        return reverse("task_detail_url", kwargs={"task_id": self.pk})
    
    def get_update_url(self):
        return reverse("task_update_url", kwargs={"obj_id": self.pk})

    def get_delete_url(self):
        return reverse("task_delete_url", kwargs={"obj_id": self.pk})

from django.contrib.auth.models import User

def get_user_name(self):
    return '{} {} | {}'.format(self.first_name, self.last_name, self.username)

User.add_to_class("__str__", get_user_name)

mekona_solution/order_control/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User



class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('order_text', 'type_of_work_fk', 'client_number', 'order_author',  'deadline', )
        widgets = {
            'deadline': forms.DateInput(attrs={'class':'form-control'}),
            # 'order_date_update': forms.SplitDateTimeWidget(attrs={'class':'form-control'}),
            # 'order_date_creation': forms.DateTimeField(attrs={'class':'form-control'}),
            'order_author': forms.HiddenInput(attrs={'class':'form-control'}),
            'order_text': forms.TextInput(attrs={'class':'form-control'}),
            'type_of_work_fk': forms.SelectMultiple(attrs={'class':'form-control'}),
            'client_number': forms.TextInput(attrs={'class':'form-control', 'placeholder':'+7(999)-999-99-99'}),
        }


class TaskForm(forms.ModelForm):
    task_executor = forms.ModelChoiceField(queryset=User.objects.all().exclude(is_staff = False), widget=forms.Select(attrs={'class':'form-control'}), label='Исполнитель')
    cost = forms.FloatField()
    class Meta:
        model = Task
        fields = ('order_fk', 'type_fk',   'task_executor', 'status','task_author', 'task_text' )
        widgets = {
            'type_fk': forms.Select(attrs={'class':'form-control'}),
            'order_fk': forms.Select(attrs={'class':'form-control'}),
            
            'task_author': forms.HiddenInput(attrs={'class':'form-control'}),
            'status': forms.Select(attrs={'class':'form-control'}),
            'task_text': forms.Textarea(attrs={'class':'form-control'}),
        }

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name']
        widgets = {
            'email' : forms.TextInput(attrs={'class':'form-control'}),
            'username': forms.TextInput(attrs={'class':'form-control', 'readonly':''}),
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
        }

mekona_solution/order_control/views.py
from django.shortcuts import render
from django.views.generic import View, ListView
from .utils import ObjUpdateMixin, ObjCreateMixin, ObjDeleteMixin
from .models import Order, Task, Profile
from django.contrib.auth.models import User
from .forms import OrderForm, TaskForm, UserUpdateForm
from django.shortcuts import render, redirect, reverse
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from django.template.loader import render_to_string

from weasyprint import HTML

# Create your views here.
def mainpage(request):
    return render(request, 'order_control/mainpage.html')

def historypage(request):
    return render(request, 'order_control/history.html')

class OrderCreate(View, ObjCreateMixin):
    model_form = OrderForm
    raise_exeption = True
    template = 'order_control/order_create_form.html'
    def get(self, request, *args, **kwargs):
        form = self.model_form(initial={'order_author': request.user})
        return render(request, self.template, context={'form': form})

    
    
class OrderUpdate(View, ObjUpdateMixin):
    model_form = OrderForm
    data = Order
    raise_exeption = True
    template = 'order_control/order_update_form.html'

class OrderDelete(View, ObjDeleteMixin):
    raise_exeption = True
    data = Order
    reverse_url = 'order_list_url'
    template = 'order_control/order_delete_form.html'

class OrderList(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'order_control/orders_list.html'

    def get_queryset(self):
        return Order.objects.all()

def order_detail(request, order_id):
    try:
        order = Order.objects.get(pk=order_id)
        context = {'order': order, 'panel': order, 'detail': True}
        # if request.user.is_authenticated:
        #     context['form'] = CommentForm
    except Order.DoesNotExist:
        raise Http404('Заказа не существует!')
    return render(request, 'order_control/order_detail.html', context)

class TaskList(ListView):
    model = Task
    temlate_name = 'order_control/task_list.html'

    def get_queryset(self):
        search_request = self.request.GET.get('search', '')

        if search_request:
            task_list = self.model.objects.filter(Q(title__icontains=search_request) | Q(text__icontains=search_request))
        else:
            task_list = self.model.objects.all()

        return task_list

class TaskCreate(View, ObjCreateMixin):
    model_form = TaskForm
    raise_exeption = True
    template = 'order_control/task_create_form.html'

    def get(self, request, *args, **kwargs):
        form = self.model_form(initial={'task_author': request.user})
        return render(request, self.template, context={'form': form})
class TaskUpdate(View, ObjUpdateMixin):
    model_form = TaskForm
    data = Task
    raise_exeption = True
    template = 'order_control/task_update_form.html'

class TaskDelete(View, ObjDeleteMixin):
    raise_exeption = True
    data = Task
    reverse_url = 'task_list_url'
    template = 'order_control/task_delete_form.html'

def task_detail(request, task_id):
    try:
        task = Task.objects.get(pk=task_id)
        context = {'task': task, 'panel': task, 'detail': True}
        # if request.user.is_authenticated:
        #     context['form'] = CommentForm
    except Task.DoesNotExist:
        raise Http404('Заказа не существует!')
    return render(request, 'order_control/task_detail.html', context)

class ClientOrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'order_control/orders_list.html'

    def get_queryset(self):
        return Order.objects.filter(order_author = self.request.user).order_by('order_date_creation')

class WorkerTaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'order_control/task_list.html'

    def get_queryset(self):
        task_list = Task.objects.filter(task_executor = self.request.user).exclude(status = 'C').order_by('task_date_creation')
        return task_list

class AdminTaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'order_control/task_list.html'

    def get_queryset(self):
        task_list = Task.objects.filter(task_author = self.request.user).exclude(status = 'C').order_by('task_date_creation')
        return task_list
        

class UserUpdateView( LoginRequiredMixin,View, ObjUpdateMixin):
    model_form = UserUpdateForm
    data = User
    raise_exeption = True
    template = 'order_control/user_account.html'
    

    def get(self, request):
        data_obj = self.data.objects.get(username=self.request.user.username)
        bound_form = self.model_form(instance=data_obj)
        return render(request, self.template, context={'form': bound_form, 'obj': data_obj})
    
    def post(self, request):
        data_obj = self.data.objects.get(username=self.request.user.username)
        bound_form = self.model_form(request.POST, instance=data_obj)

        if bound_form.is_valid():
            new_obj = bound_form.save()
            return redirect('profile_detail_url')
        return render(request, self.template, context={'form': bound_form, 'obj': data_obj})

def profile(request):
    data_obj = User.objects.get(pk=request.user.id)
    return render(request, template_name='order_control/user_account.html', )

# def html_to_pdf_view(request, order_id):
#     try:
#         order = Order.objects.get(pk=order_id)
#         context = {'order': order}
#     except Order.DoesNotExist:
#         raise Http404('Заказа не существует!')
#     html_string = render_to_string('order_control/pdf_template.html', context)

#     html = HTML(string=html_string)
#     html.write_pdf(target='/tmp/mypdf.pdf');

#     fs = FileSystemStorage('/tmp')
#     with fs.open('mypdf.pdf') as pdf:
#         response = HttpResponse(pdf, content_type='application/pdf')
#         response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'
#         return response

#     return response

mekona_solution/order_control/templates/order_control/order_create_form.html
{% extends 'base.html' %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-7">


        <form action="{% url 'order_create_url' %}" method="POST">
            {% csrf_token %}
            {% for field in form %}

            {% if field.errors %}
            <div class="alert alert-danger" role="alert">
                {{field.errors}}
            </div>
            {% endif %}
            {% if field.is_hidden %}
            {# Don't render label #}
            {% else %}
            {{ field.label}}
            {% endif %}
            {{ field}}

            {% endfor %}
            <button class="btn btn-primary" type="submit">Добавить</button>
        </form>
    </div>
</div>
<!-- Fengyuan Chen's Datepicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
    integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
    integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>


<script>
    $(function () {
        $("#id_deadline").datepicker({
            format: 'dd.mm.yyyy',
        });
    });
</script>



{% endblock content %}

mekona_solution/order_control/templates/order_control/order_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-5 mb-5 justify-content-center">
    <h3>Заказ №{{order.id}}</h3>
</div>
<form>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputEmail4">Заказчик</label>
            <label class="form-control" id="inputEmail4">{{order.order_author.first_name}}
                {{order.order_author.last_name}}</label>
        </div>
        <div class="form-group col-md-6">
            <label for="inputPassword4">Дата заказа</label>
            <label class="form-control" id="inputPassword4">{{order.order_date_creation}}</label>
        </div>
    </div>
    <div class="form-group">
        <label for="inputAddress">Текст заказа</label>
        <textarea class="form-control" id="inputAddress">{{order.order_text}}</textarea>
    </div>

    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="inputAddress2">Виды работ</label>

            <ul class="list-group" id="inputAddress2">
                {% if order.type_of_work_fk.all %}
                {% for type in order.type_of_work_fk.all %}
                <li class="list-group-item">{{type.name_of_type}} </li>
                {% endfor %}
                {% else %}
                <li class="list-group-item">Не выбран ни один вид работ! </li>
                {% endif %}
            </ul>

        </div>
        <div class="form-group col-md-4">
            <label for="inputCity">Номер обратной связи</label>
            <label class="form-control" id="inputCity">{{order.client_number}}</label>
        </div>
        <div class="form-group col-md-4">
            <label for="inputZip">Дата окончания</label>
            <label class="form-control" id="inputZip">{{order.deadline}}</label>
        </div>
    </div>

</form>


{% if order.task_set.all %}
<div class="row justify-content-center">
    
    <h3>Здесь вы можете отследить работы по вашему заказу.</h3>
    
</div>
<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Автор</th>
            <th scope="col">Тип работ</th>
            <th scope="col">Дата создания</th>
            <th scope="col">Текст</th>
            <th scope="col">Дата окончания</th>
            <th scope="col">Исполнитель</th>
            <th scope="col">Статус</th>
        </tr>
    </thead> 
    <tbody>
        {% for task in order.task_set.all %}
        
        <tr>
            <th scope="row">{{task.id}}</th>
            <td>
                {% if task.task_author.first_name %}
                {{task.task_author.first_name}} {{task.task_author.last_name}}
                {% else %}
                {{task.task_author}}
                {% endif %}
                

            </td>
            <td>{{task.type_fk}}</td>
            <td>{{task.task_date_creation}}</td>
            <td>{{task.task_text|truncatewords:4}}</td>
            <td>
                
                {% if task.task_date_comleate %}
                {{task.task_date_comleate}}
                {% else %}
                Задача в процессе выполнения
                {% endif %}
                    
            </td>
            <td>
                
                {% if task.task_executor.first_name %}
                {{task.task_executor.first_name}} {{task.task_executor.last_name}}
                {% else %}
                {{task.task_executor}}
                {% endif %}
                    
            </td>
            <td>{{task.get_status_display}}</td>
            
          </tr>
        {% endfor %}
    </tbody>
  </table>

{% else %}
<div class="row justify-content-center mt-5">
    
    
    <h3>Ваш заказ в обработке</h3>
    
</div>
{% endif %}
    
{% endblock content%}

mekona_solution/order_control/templates/order_control/order_update_form.html
{% extends 'base.html' %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

<form action="{{ obj.get_update_url }}" method = "POST">
{% csrf_token %}
    {% for field in form %}
    {% if field.errors %}
        <div class="alert alert-danger" role="alert">
            {{field.errors}}
        </div>
        {% endif %}
        {% if field.is_hidden %}
            {# Don't render label #}
        {% else %}
        {{ field.label}}
        {% endif %}
        {{ field}}
        
        {% endfor %}
    <button class="btn btn-primary" type="submit">Изменить</button>
</form>
<!-- Fengyuan Chen's Datepicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

<script>
    $(function () {
      $("#id_deadline").datepicker({
        format:'dd.mm.yyyy',
      });
    });
  </script>
{% endblock content %}

mekona_solution/order_control/templates/order_control/pdf_template.html
<html>
<head>
  <title>Test</title>
  <style>
    body {
      background-color: #f7f7f7;
    }
  </style>
  <meta charset="UTF-8">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
		integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
		integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
		integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
		crossorigin="anonymous"></script>
</head>
<body>
    <div class="row mt-5 mb-5 justify-content-center">
        <h3>Заказ №{{order.id}}</h3>
    </div>
    <form>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputEmail4">Заказчик</label>
                <label class="form-control" id="inputEmail4">{{order.order_author.first_name}}
                    {{order.order_author.last_name}}</label>
            </div>
            <div class="form-group col-md-6">
                <label for="inputPassword4">Дата заказа</label>
                <label class="form-control" id="inputPassword4">{{order.order_date_creation}}</label>
            </div>
        </div>
        <div class="form-group">
            <label for="inputAddress">Текст заказа</label>
            <textarea class="form-control" id="inputAddress">{{order.order_text}}</textarea>
        </div>
    
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="inputAddress2">Виды работ</label>
    
                <ul class="list-group" id="inputAddress2">
                    {% if order.type_of_work_fk.all %}
                    {% for type in order.type_of_work_fk.all %}
                    <li class="list-group-item">{{type.name_of_type}} </li>
                    {% endfor %}
                    {% else %}
                    <li class="list-group-item">Не выбран ни один вид работ! </li>
                    {% endif %}
                </ul>
    
            </div>
            <div class="form-group col-md-4">
                <label for="inputCity">Номер обратной связи</label>
                <label class="form-control" id="inputCity">{{order.client_number}}</label>
            </div>
            <div class="form-group col-md-4">
                <label for="inputZip">Дата окончания</label>
                <label class="form-control" id="inputZip">{{order.deadline}}</label>
            </div>
        </div>
    
    </form>
    
    
    {% if order.task_set.all %}
    <div class="row justify-content-center">
        
        <h3>Здесь вы можете отследить работы по вашему заказу.</h3>
        
    </div>
    <table class="table mt-5">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Автор</th>
                <th scope="col">Тип работ</th>
                <th scope="col">Дата создания</th>
                <th scope="col">Текст</th>
                <th scope="col">Дата окончания</th>
                <th scope="col">Исполнитель</th>
                <th scope="col">Статус</th>
            </tr>
        </thead> 
        <tbody>
            {% for task in order.task_set.all %}
            
            <tr>
                <th scope="row">{{task.id}}</th>
                <td>
                    {% if task.task_author.first_name %}
                    {{task.task_author.first_name}} {{task.task_author.last_name}}
                    {% else %}
                    {{task.task_author}}
                    {% endif %}
                    
    
                </td>
                <td>{{task.type_fk}}</td>
                <td>{{task.task_date_creation}}</td>
                <td>{{task.task_text|truncatewords:4}}</td>
                <td>
                    
                    {% if task.task_date_comleate %}
                    {{task.task_date_comleate}}
                    {% else %}
                    Задача в процессе выполнения
                    {% endif %}
                        
                </td>
                <td>
                    
                    {% if task.task_executor.first_name %}
                    {{task.task_executor.first_name}} {{task.task_executor.last_name}}
                    {% else %}
                    {{task.task_executor}}
                    {% endif %}
                        
                </td>
                <td>{{task.get_status_display}}</td>
                
              </tr>
            {% endfor %}
        </tbody>
      </table>
    
    {% else %}
    <div class="row justify-content-center mt-5">
        
        
        <h3>Ваш заказ в обработке</h3>
        
    </div>
    {% endif %}
        
</body>
</html>

mekona_solution/order_control/templates/order_control/task_list.html
{% extends 'base.html' %}


{% block content %}
{% if task_list %}
<div class="row justify-content-center">

<h2>Задачи</h2>
<table class="table mt-5">
<thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Автор</th>
    <th scope="col">Тип работ</th>
    <th scope="col">Дата создания</th>
    <th scope="col">Текст</th>
    <th scope="col">Дата окончания</th>
    <th scope="col">Исполнитель</th>
    <th scope="col">Статус</th>
  </tr>
</thead> 
<tbody>
    {% for task in task_list %}
    <tr>
        <th scope="row">{{task.id}}</th>
        <td>
          {% if task.task_author.first_name %}
            {{task.task_author.first_name}} {{task.task_author.last_name}}
            {% else %}
            {{task.task_author}}
            {% endif %}

        </td>
        <td>{{task.type_fk}}</td>
        <td>{{task.task_date_creation}}</td>
        <td>{{task.task_text|truncatewords:4}}</td>
        <td>
            
            {% if task.task_date_comleate %}
            {{task.task_date_comleate}}
            {% else %}
            Задача в процессе выполнения
            {% endif %}
                
        </td>
        <td>
            
            {% if task.task_executor.first_name %}
            {{task.task_executor.first_name}} {{task.task_executor.last_name}}
            {% else %}
            {{task.task_executor}}
            {% endif %}
                
        </td>
        <td>{{task.get_status_display}}</td>
        <th scope="col"><a class="btn btn-info" href="{{ task.get_absolute_url }}">Открыть</a></th>
      </tr>
    {% endfor %}
</tbody>
</table>
</div>
{% else %}
<div class="row justify-content-center">
  <h3>Нет ни одной активной задачи</h3>
  
</div>
{% endif %}


{% endblock content %}